#!/usr/bin/env node
// build-widget.mjs — emit the framework-agnostic <ship-helpbot> web component, themed from brand.json.
//
// Writes a single self-contained .js file that registers a custom element:
//     <ship-helpbot src="/guide-index.json" endpoint="/api/ask-docs"></ship-helpbot>
//
// The widget renders a floating "Ask the guide" launcher + panel inside a Shadow DOM
// (style-isolated from the host app). It loads the guide index, POSTs questions to the
// reference /api/ask-docs route, and renders the answer with clickable citations that
// deep-link to the rendered guide's heading anchors. No build step, no dependencies,
// no framework — drop the <script> + the tag into ANY app.
//
// Theming: colors/fonts come from docs/brand.json, baked into the component's :host
// CSS custom properties at build time AND overridable at runtime via host CSS
// (--shb-brand, --shb-bg, ...). Never purple by default. No backdrop-filter, no SVG
// feTurbulence (both hang some renderers) — per the ship pack's HTML rules.
//
// Usage:
//   node build-widget.mjs --out public/ship-helpbot.js [--brand docs/brand.json] \
//        [--endpoint /api/ask-docs] [--src /guide-index.json]
//
// Part of the ship-helpbot skill (the "ship" pack).

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

const args = process.argv.slice(2);
const opt = (n, d) => { const i = args.indexOf(n); return i !== -1 ? args[i + 1] : d; };

const OUT = opt("--out", "public/ship-helpbot.js");
const BRAND = opt("--brand", "docs/brand.json");
const DEF_ENDPOINT = opt("--endpoint", "/api/ask-docs");
const DEF_SRC = opt("--src", "/guide-index.json");

// ---------- theme tokens (no purple defaults) ----------
const DEFAULTS = {
  bg: "#0b0d10", surface: "#13171e", border: "#232a33",
  text: "#e7edf3", muted: "#90a0b0", heading: "#f5f9fd",
  brand: "#2f7dff", accent: "#ffc24b", "accent-ink": "#9fd0e8",
};
const FONT_DEFAULTS = { body: "Hanken Grotesk", mono: "JetBrains Mono" };

let brand = null;
if (existsSync(BRAND)) {
  try { brand = JSON.parse(readFileSync(BRAND, "utf8")); }
  catch (e) { console.error(`build-widget: could not parse ${BRAND} (${e.message}); using defaults`); }
}
const colors = { ...DEFAULTS, ...((brand && brand.colors) || {}) };
const fonts = { ...FONT_DEFAULTS, ...((brand && brand.fonts) || {}) };
const productName = (brand && brand.name) || "the guide";

// single-quote the family name: the whole token is embedded inside a double-quoted JS string,
// so double quotes here would terminate it. Single quotes are valid in CSS font-family.
const fontStack = (n, kind) =>
  `'${n}',` + (kind === "mono" ? 'ui-monospace,SFMono-Regular,monospace' : "ui-sans-serif,system-ui,sans-serif");

// host-overridable custom properties, prefixed --shb-* to avoid collisions
const hostVars = [
  `--shb-bg:${colors.bg}`, `--shb-surface:${colors.surface}`, `--shb-border:${colors.border}`,
  `--shb-text:${colors.text}`, `--shb-muted:${colors.muted}`, `--shb-heading:${colors.heading}`,
  `--shb-brand:${colors.brand}`, `--shb-accent:${colors.accent}`, `--shb-accent-ink:${colors["accent-ink"]}`,
  `--shb-font:${fontStack(fonts.body, "body")}`, `--shb-mono:${fontStack(fonts.mono, "mono")}`,
].join(";");

const js = String.raw`/* ship-helpbot — embeddable "ask the guide" web component.
 * Generated by the ship-helpbot skill from docs/brand.json. Self-contained, no deps.
 * Theme via host CSS: ship-helpbot{ --shb-brand:#0056D2; --shb-accent:#FFDD00; }
 *
 *   <script src="/ship-helpbot.js" defer></script>
 *   <ship-helpbot src="${DEF_SRC}" endpoint="${DEF_ENDPOINT}"></ship-helpbot>
 *
 * Attributes:
 *   src       URL of guide-index.json (default "${DEF_SRC}")
 *   endpoint  POST route that answers questions (default "${DEF_ENDPOINT}")
 *   label     launcher button text (default "Ask the guide")
 *   guide     base URL of the rendered HTML guide for citation links (default "")
 *   open      present => start expanded
 */
(() => {
  if (customElements.get("ship-helpbot")) return;
  const HOST_VARS = "${hostVars}";
  const PRODUCT = ${JSON.stringify(productName)};

  const css = ` + "`" + String.raw`
    :host{ ${"${HOST_VARS}".replace(/;/g, ";\n      ")}
      all:initial; position:fixed; right:20px; bottom:20px; z-index:2147483000;
      font-family:var(--shb-font); color:var(--shb-text); }
    *{ box-sizing:border-box; }
    button{ font:inherit; cursor:pointer; }
    .launch{ display:inline-flex; align-items:center; gap:8px; border:0; border-radius:999px;
      padding:12px 18px; background:var(--shb-brand); color:#fff; font-weight:600; font-size:14px;
      box-shadow:0 6px 22px rgba(0,0,0,.35); transition:transform .15s ease, filter .15s ease; }
    .launch:hover{ transform:translateY(-1px); filter:brightness(1.06); }
    .launch svg{ width:18px; height:18px; }
    .panel{ position:fixed; right:20px; bottom:20px; width:min(420px,calc(100vw - 40px));
      height:min(620px,calc(100vh - 40px)); display:none; flex-direction:column; overflow:hidden;
      background:var(--shb-bg); border:1px solid var(--shb-border); border-radius:16px;
      box-shadow:0 24px 60px rgba(0,0,0,.5); }
    :host([data-open]) .panel{ display:flex; }
    :host([data-open]) .launch{ display:none; }
    .head{ display:flex; align-items:center; gap:10px; padding:14px 16px;
      border-bottom:1px solid var(--shb-border); background:var(--shb-surface); }
    .dot{ width:9px; height:9px; border-radius:50%; background:var(--shb-accent); box-shadow:0 0 0 4px color-mix(in srgb,var(--shb-accent) 22%, transparent); }
    .title{ font-weight:700; color:var(--shb-heading); font-size:14px; }
    .sub{ color:var(--shb-muted); font-size:12px; }
    .x{ margin-left:auto; background:transparent; border:0; color:var(--shb-muted); font-size:20px; line-height:1; padding:4px 8px; border-radius:8px; }
    .x:hover{ background:var(--shb-border); color:var(--shb-heading); }
    .log{ flex:1; overflow-y:auto; padding:16px; display:flex; flex-direction:column; gap:14px; }
    .msg{ max-width:90%; font-size:14px; line-height:1.55; }
    .msg.user{ align-self:flex-end; background:var(--shb-brand); color:#fff; padding:9px 13px; border-radius:14px 14px 4px 14px; }
    .msg.bot{ align-self:flex-start; color:var(--shb-text); }
    .msg.bot p{ margin:0 0 8px; }
    .msg.bot code{ font-family:var(--shb-mono); background:var(--shb-surface); padding:1px 5px; border-radius:5px; font-size:12.5px; }
    .cites{ display:flex; flex-wrap:wrap; gap:6px; margin-top:8px; }
    .cite{ display:inline-flex; align-items:center; gap:5px; text-decoration:none; font-size:12px; font-weight:600;
      color:var(--shb-accent-ink); background:var(--shb-surface); border:1px solid var(--shb-border);
      padding:3px 9px; border-radius:999px; }
    .cite:hover{ border-color:var(--shb-brand); }
    .hint{ color:var(--shb-muted); font-size:13px; }
    .chips{ display:flex; flex-wrap:wrap; gap:6px; margin-top:10px; }
    .chip{ font-size:12px; color:var(--shb-text); background:var(--shb-surface); border:1px solid var(--shb-border);
      padding:6px 10px; border-radius:999px; }
    .chip:hover{ border-color:var(--shb-brand); color:var(--shb-heading); }
    .err{ color:#ff8a8a; font-size:13px; }
    .typing{ display:inline-flex; gap:4px; }
    .typing i{ width:6px; height:6px; border-radius:50%; background:var(--shb-muted); animation:b 1s infinite; }
    .typing i:nth-child(2){ animation-delay:.15s; } .typing i:nth-child(3){ animation-delay:.3s; }
    @keyframes b{ 0%,80%,100%{ opacity:.3; } 40%{ opacity:1; } }
    form{ display:flex; gap:8px; padding:12px; border-top:1px solid var(--shb-border); background:var(--shb-surface); }
    input{ flex:1; font:inherit; font-size:14px; color:var(--shb-text); background:var(--shb-bg);
      border:1px solid var(--shb-border); border-radius:10px; padding:10px 12px; outline:none; }
    input:focus{ border-color:var(--shb-brand); }
    .send{ border:0; border-radius:10px; background:var(--shb-brand); color:#fff; padding:0 14px; font-weight:600; }
    @media (prefers-reduced-motion: reduce){ *{ animation:none!important; transition:none!important; } }
  ` + "`" + String.raw`;

  const ICON = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>';

  class ShipHelpbot extends HTMLElement {
    connectedCallback(){
      this.src = this.getAttribute("src") || "${DEF_SRC}";
      this.endpoint = this.getAttribute("endpoint") || "${DEF_ENDPOINT}";
      this.guideBase = this.getAttribute("guide") || "";
      const label = this.getAttribute("label") || "Ask " + PRODUCT;
      const root = this.attachShadow({ mode:"open" });
      root.innerHTML =
        '<style>'+css+'</style>'+
        '<button class="launch" part="launch">'+ICON+'<span>'+label+'</span></button>'+
        '<section class="panel" role="dialog" aria-label="Ask the guide">'+
          '<div class="head"><span class="dot"></span>'+
            '<div><div class="title">'+label+'</div><div class="sub">Answers cite the guide</div></div>'+
            '<button class="x" aria-label="Close">×</button></div>'+
          '<div class="log"></div>'+
          '<form><input type="text" placeholder="Ask a question…" autocomplete="off"/>'+
            '<button class="send" type="submit">Ask</button></form>'+
        '</section>';
      this.$log = root.querySelector(".log");
      this.$input = root.querySelector("input");
      root.querySelector(".launch").onclick = () => this.toggle(true);
      root.querySelector(".x").onclick = () => this.toggle(false);
      root.querySelector("form").onsubmit = (e) => { e.preventDefault(); this.ask(this.$input.value); };
      this.greet();
      if (this.hasAttribute("open")) this.toggle(true);
    }
    toggle(on){ if (on) this.setAttribute("data-open",""); else this.removeAttribute("data-open"); if (on) this.$input.focus(); }
    greet(){
      const seeds = ["How do I get started?","What can I do here?","How do I add a project?"];
      const chips = seeds.map(s => '<button class="chip">'+s+'</button>').join("");
      this.$log.innerHTML = '<div class="msg bot"><p>Hi! Ask me anything about '+PRODUCT+'. '+
        'I answer from the guide and link you to the exact section.</p><div class="chips">'+chips+'</div></div>';
      this.$log.querySelectorAll(".chip").forEach(c => c.onclick = () => this.ask(c.textContent));
    }
    add(role, html){
      const d = document.createElement("div"); d.className = "msg "+role; d.innerHTML = html;
      this.$log.appendChild(d); this.$log.scrollTop = this.$log.scrollHeight; return d;
    }
    async ask(q){
      q = (q||"").trim(); if (!q) return;
      this.$input.value = "";
      this.add("user", this.escape(q));
      const thinking = this.add("bot", '<span class="typing"><i></i><i></i><i></i></span>');
      try{
        const res = await fetch(this.endpoint, {
          method:"POST", headers:{ "content-type":"application/json" },
          body: JSON.stringify({ question:q, src:this.src }),
        });
        if (!res.ok) throw new Error("HTTP "+res.status);
        const data = await res.json();
        thinking.innerHTML = this.render(data);
        thinking.querySelectorAll(".chip").forEach(c => c.onclick = () => this.ask(c.textContent));
      }catch(err){
        thinking.innerHTML = '<p class="err">Sorry — I couldn\'t reach the answer service ('+
          this.escape(err.message)+'). The guide is still available directly.</p>';
      }
    }
    render(data){
      const answer = (data && data.answer) || "I couldn't find that in the guide.";
      const cites = (data && data.citations) || [];
      let html = '<p>'+this.mdLite(answer)+'</p>';
      if (cites.length){
        html += '<div class="cites">'+cites.map(c => {
          const href = (this.guideBase || "") + "#" + encodeURIComponent(c.anchor||c.id||"");
          return '<a class="cite" href="'+href+'" target="_blank" rel="noopener">▸ '+this.escape(c.title||c.anchor||"section")+'</a>';
        }).join("")+'</div>';
      }
      return html;
    }
    mdLite(s){ // minimal, safe: escape then re-apply **bold** and \`code\`
      s = this.escape(s);
      s = s.replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>");
      s = s.replace(/` + "`" + String.raw`([^` + "`" + String.raw`]+)` + "`" + String.raw`/g, "<code>$1</code>");
      return s.replace(/\n{2,}/g, "</p><p>").replace(/\n/g, "<br>");
    }
    escape(s){ return String(s).replace(/[&<>"]/g, m => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m])); }
  }
  customElements.define("ship-helpbot", ShipHelpbot);
})();
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, js, "utf8");
console.log(
  `build-widget: wrote ${OUT}  (themed from ${brand ? BRAND : "defaults"}, product="${productName}")\n` +
  `  embed:  <script src="/${OUT.split("/").pop()}" defer></script>\n` +
  `          <ship-helpbot src="${DEF_SRC}" endpoint="${DEF_ENDPOINT}"></ship-helpbot>`
);
